### ISSUE TITLE
How to log events from external application

### ISSUE THREAD

**Issue by LouisKraemer** [samuraitruong/yeelight#14]
First of all, thanks for this package, it's really working great.

I've got two questions : 

- Is there any way to detect event happening but from the original application ?

- I tried to add the logger parameter to the discover method but I can't seem to log any event

```
const y = require("yeelight-awesome");
const discover = new y.Discover({
    port: 1982,
    debug: true
  }, y.logger);
```

Am I using it the wrong way ?

Thanks in advance

**Comment by samuraitruong** [comment]
hi @Weegle99 ,
y.logger is default to console . log. 

if you prefer your own logger just need to . implement the custom logger.

https://www.npmjs.com/package/yeelight-awesome#logger

**Comment by LouisKraemer** [comment]
Thanks for the quick response !

What about handling event on the lamp (for example, if someone is using the official app, I would like to receive the update as well) ? Is it possible ?
