### ISSUE TITLE
How to set white color

### ISSUE THREAD

**Issue by fatshotty** [samuraitruong/yeelight#6]
Hi, first of all good job.
I wonder: I cannot set white color to my Yeelight Bulb.
I'm trying:
```
yeelight.setRGB( new Color(255,255,255) ).then( () => {
...
});
```
but I see a violet color.
What am I doing wrong?
Thanks in advance

**Comment by maxmilton** [comment]
I've been using:

```js
yeelight.setHSV(0, 0, 'smooth', 1000);
```

**Comment by samuraitruong** [comment]
Hi @fatshotty ,

setRGB is recommended to use when you want to set the color for the light,

The white color is a special case, I use below code
```js

yeelight.setCtAbx(5000, "sudden", 1000);

```

The first parameter is the temperature of the light, 5000 will give you a natural light.

Also, I think Color function convert color from RGB to number is not perfect, I note that I do more testing around it later. Thanks

**Comment by fatshotty** [comment]
thank you.
It works using `setHSV` or `setCtAbx`
Yes, I think the `setRGB` function should be fixed :)

Thanks again
